// Centralized Comprehensive Local Database Registry
const FESTIVAL_DATA_REGISTRY = {
    "Rock im Park": [
        { name: "Iron Maiden", genre: "Heavy Metal" },
        { name: "Linkin Park", genre: "Nu Metal" },
        { name: "Volbeat", genre: "Heavy Metal" },
        { name: "A Perfect Circle", genre: "Alternative Rock" },
        { name: "Alter Bridge", genre: "Hard Rock" },
        { name: "Ankor", genre: "Alternative Metal" },
        { name: "Anna Grey", genre: "Pop" },
        { name: "Architects", genre: "Metalcore" },
        { name: "BABYMETAL", genre: "Alternative Metal" },
        { name: "Bad Nerves", genre: "Garage Punk" },
        { name: "Bad Omens", genre: "Alternative Metal" },
        { name: "Basement", genre: "Emocore" },
        { name: "Bilmuri", genre: "Alternative Rock" },
        { name: "Black Veil Brides", genre: "Hard Rock" },
        { name: "Blood Incantation", genre: "Death Metal" },
        { name: "Bloodywood", genre: "Nu Metal / Metalcore" },
        { name: "Boundaries", genre: "Metalcore" },
        { name: "Breaking Benjamin", genre: "Alternative Metal" },
        { name: "Bury Tomorrow", genre: "Metalcore" },
        { name: "Bush", genre: "Alternative Rock" },
        { name: "Catch Your Breath", genre: "Metalcore" },
        { name: "Danko Jones", genre: "Hard Rock" },
        { name: "Don Broco", genre: "Alternative Rock" },
        { name: "Drain", genre: "Hardcore Punk" },
        { name: "Dying Wish", genre: "Metalcore" },
        { name: "Ecca Vandal", genre: "Post-Punk" },
        { name: "Ego Kill Talent", genre: "Alternative Rock" },
        { name: "Electric Callboy", genre: "Electronicore" },
        { name: "Finch", genre: "Post-Hardcore" },
        { name: "Gatecreeper", genre: "Death Metal" },
        { name: "H-Blockx", genre: "Rap Rock" },
        { name: "High Vis", genre: "Post-Punk" },
        { name: "Hollywood Undead", genre: "Rap Rock" },
        { name: "Ice Nine Kills", genre: "Metalcore" },
        { name: "Kublai Khan TX", genre: "Beatdown Hardcore" },
        { name: "Landmvrks", genre: "Metalcore" },
        { name: "Letlive.", genre: "Post-Hardcore" },
        { name: "Limp Bizkit", genre: "Nu Metal" },
        { name: "Loathe", genre: "Metalcore" },
        { name: "Magnolia Park", genre: "Alternative Metal" },
        { name: "Malevolence", genre: "Metalcore" },
        { name: "Marteria", genre: "Pop Rap" },
        { name: "Mastodon", genre: "Progressive Sludge Metal" },
        { name: "Max Grimm", genre: "Ambient" },
        { name: "Mehnersmoos", genre: "Rap" },
        { name: "Mouth Culture", genre: "Indie Rock" },
        { name: "Palaye Royale", genre: "Glam Rock" },
        { name: "Paleface Swiss", genre: "Deathcore" },
        { name: "Papa Roach", genre: "Alternative Metal" },
        { name: "President", genre: "Alternative Metal" },
        { name: "Return To Dust", genre: "Alternative Rock" },
        { name: "Sabaton", genre: "Power Metal" },
        { name: "Set It Off", genre: "Pop Rock" },
        { name: "Slay Squad", genre: "Rap Metal" },
        { name: "Social Distortion", genre: "Punk Rock" },
        { name: "Sondaschule", genre: "Ska Punk" },
        { name: "TX2", genre: "Alternative Metal" },
        { name: "TesseracT", genre: "Progressive Metal" },
        { name: "The Butcher Sisters", genre: "Metalcore" },
        { name: "The Funeral Portrait", genre: "Alternative Rock" },
        { name: "The Hives", genre: "Garage Rock" },
        { name: "The Offspring", genre: "Pop Punk" },
        { name: "The Plot In You", genre: "Metalcore" },
        { name: "The Pretty Reckless", genre: "Hard Rock" },
        { name: "The Story So Far", genre: "Pop Punk" },
        { name: "The Subways", genre: "Garage Rock" },
        { name: "Thornhill", genre: "Alternative Metal" },
        { name: "Three Days Grace", genre: "Post-grunge" },
        { name: "Tom Morello", genre: "Alternative Rock" },
        { name: "Trivium", genre: "Melodic Metalcore" },
        { name: "Wargasm", genre: "Nu Metal" },
        { name: "We Came As Romans", genre: "Metalcore" },
        { name: "Within Temptation", genre: "Symphonic Metal" }
    ],
    "Wacken Open Air": [
        { name: "Def Leppard", genre: "Hard Rock" },
        { name: "Hämatom", genre: "Industrial Groove Metal" },
        { name: "Judas Priest", genre: "Heavy Metal" },
        { name: "Sabaton", genre: "Power Metal" },
        { name: "5th Avenue", genre: "Hard Rock" },
        { name: "9mm Headshot", genre: "Hard Rock" },
        { name: "Ad Infinitum", genre: "Symphonic Metal" },
        { name: "Airbourne", genre: "Hard Rock" },
        { name: "Alcest", genre: "Blackgaze" },
        { name: "Alestorm", genre: "Folk Metal" },
        { name: "Alfahanne", genre: "Melodic Black Metal/Rock" },
        { name: "Alien Ant Farm", genre: "Alternative Rock" },
        { name: "Alien Rockin‘ Explosion", genre: "Hard Rock" },
        { name: "Allt", genre: "Metalcore" },
        { name: "Anaal Nathrakh", genre: "Black Metal" },
        { name: "Angelus Apatrida", genre: "Thrash Metal" },
        { name: "Animals As Leaders", genre: "Progressive Metal" },
        { name: "Any Given Day", genre: "Metalcore" },
        { name: "Arch Enemy", genre: "Melodic Death Metal" },
        { name: "Arroganz", genre: "Black Metal / Death Metal" },
        { name: "Ashed Winter", genre: "Thrash / Death Metal" },
        { name: "Asrock", genre: "Hard Rock" },
        { name: "Battlecreek", genre: "Thrash Metal" },
        { name: "Bear McCreary", genre: "Film Soundtracks" },
        { name: "Blaas Of Glory", genre: "Heavy Metal" },
        { name: "Black Label Society", genre: "Southern Metal" },
        { name: "Black Tish", genre: "Industrial Metal" },
        { name: "Blanket Hill", genre: "Hardcore Punk" },
        { name: "Bleed From Within", genre: "Metalcore" },
        { name: "Blood Command", genre: "Hardcore Punk" },
        { name: "Blood Fire Death", genre: "Tribute To Bathory" },
        { name: "Blood Red Throne", genre: "Death Metal" },
        { name: "Born Broken", genre: "Deathcore" },
        { name: "Broken By The Scream", genre: "Kawaii Metal" },
        { name: "Brunhilde", genre: "Hard Rock" },
        { name: "Castle Rat", genre: "Doom Metal" },
        { name: "Chaosbay", genre: "Progressive Metal" },
        { name: "Corrosion Of Conformity", genre: "Stoner Metal" },
        { name: "Craft", genre: "Black Metal" },
        { name: "Crematory", genre: "Gothic Metal" },
        { name: "Crimson Glory", genre: "Heavy Metal" },
        { name: "Cruachan", genre: "Folk Metal" },
        { name: "Crypt Sermon", genre: "Epic Doom Metal" },
        { name: "Cursed Abyss", genre: "Metalcore / Groove Metal" },
        { name: "Danko Jones", genre: "Hard Rock" },
        { name: "Dead By April", genre: "Alternative Metal" },
        { name: "Deafheaven", genre: "Blackgaze" },
        { name: "Deflag", genre: "Metalcore" },
        { name: "Diabolisches Werk", genre: "Death Metal" },
        { name: "Dieter Birr", genre: "Rock" },
        { name: "Dirty Shirt", genre: "Nu Metal" },
        { name: "Divlje Jagode", genre: "Hard Rock" },
        { name: "Dritte Wahl", genre: "Punk Rock" },
        { name: "Dubioza Kolektiv", genre: "Reggae" },
        { name: "Einherjer", genre: "Viking Metal" },
        { name: "Electric Bassboy", genre: "Electronic" },
        { name: "Eläkeläiset", genre: "Humppa" },
        { name: "Emperor", genre: "Symphonic Black Metal" },
        { name: "Employed To Serve", genre: "Metalcore" },
        { name: "Europe", genre: "Hard Rock" },
        { name: "Evil Jared", genre: "Rock / DJ Set" },
        { name: "Expellow", genre: "Metalcore" },
        { name: "Faun", genre: "Medieval Rock" },
        { name: "Finsterforst", genre: "Viking Metal" },
        { name: "Firespawn", genre: "Death Metal" },
        { name: "Fit For An Autopsy", genre: "Deathcore" },
        { name: "Focus.", genre: "Punk Rock" },
        { name: "Future Palace", genre: "Post-Hardcore" },
        { name: "Gidora", genre: "Death / Groove Metal" },
        { name: "Grand Magus", genre: "Heavy Metal" },
        { name: "Guilt Trip", genre: "Metalcore / Hardcore" },
        { name: "Gutalax", genre: "Goregrind" },
        { name: "Gágor", genre: "Death / Thrash Metal" },
        { name: "H-Blockx", genre: "Rap Rock" },
        { name: "Hackneyed", genre: "Death Metal" },
        { name: "Haine", genre: "Deathcore" },
        { name: "Hardline", genre: "Hard Rock" },
        { name: "Hatebreed", genre: "Metalcore" },
        { name: "Heartless Human Harvest", genre: "Deathcore" },
        { name: "Heavysaurus", genre: "Heavy Metal" },
        { name: "In Flames", genre: "Melodic Death Metal" },
        { name: "Insanity Alert", genre: "Crossover Thrash" },
        { name: "Kadavar", genre: "Stoner Rock" },
        { name: "Katerfahrt", genre: "Mittelalter Rock" },
        { name: "Kim Dracula", genre: "Alternative Metal" },
        { name: "Kittie", genre: "Alternative Metal" },
        { name: "Kupfergold", genre: "Folk" },
        { name: "Kärbholz", genre: "Punk Rock" },
        { name: "Lacuna Coil", genre: "Alternative Metal" },
        { name: "Lagwagon", genre: "Skate Punk" },
        { name: "Lamb Of God", genre: "Groove Metal" },
        { name: "Life Of Agony", genre: "Alternative Metal" },
        { name: "Lovebites", genre: "Power Metal" },
        { name: "Luna Kills", genre: "Alternative Rock" },
        { name: "Mambo Kurt", genre: "Musical Parody" },
        { name: "Manntra", genre: "Folk Metal" },
        { name: "Mantar", genre: "Sludge Metal" },
        { name: "Metaklapa", genre: "Iron Maiden A cappella Tribute" },
        { name: "Minotaurus", genre: "Folk Metal" },
        { name: "Misery Index", genre: "Death Metal" },
        { name: "Misþyrming + Nergal (Perform Sventevith)", genre: "Black Metal" },
        { name: "Morphide", genre: "Progressive Metalcore" },
        { name: "Mr. Hurley & Die Pulveraffen", genre: "Folk Rock" },
        { name: "Municipal Waste", genre: "Crossover Thrash" },
        { name: "Nevermore", genre: "Progressive Metal" },
        { name: "Orbit Culture", genre: "Melodic Death Metal" },
        { name: "Our Promise", genre: "Metalcore" },
        { name: "P.O.D.", genre: "Rap Rock" },
        { name: "Paleface Swiss", genre: "Deathcore" },
        { name: "Paradise Lost", genre: "Gothic Metal" },
        { name: "Phantom", genre: "Thrash Metal" },
        { name: "Pig Destroyer", genre: "Grindcore" },
        { name: "Poison The Preacher", genre: "Thrash Metal" },
        { name: "Powerwolf", genre: "Power Metal" },
        { name: "President", genre: "Alternative Metal" },
        { name: "Ricky Warwick", genre: "Hardrock / Heavy Metal" },
        { name: "Rise of the Shadows", genre: "Melodic Death Metal" },
        { name: "Rose Tattoo", genre: "Hard Rock" },
        { name: "Running Wild", genre: "Heavy Metal" },
        { name: "Sacred Steel", genre: "Heavy Metal" },
        { name: "Sagenbringer", genre: "Folk Metal" },
        { name: "Savatage", genre: "Heavy Metal" },
        { name: "Saviourself", genre: "Metalcore" },
        { name: "Saxon", genre: "Heavy Metal" },
        { name: "Sepultura", genre: "Groove Metal" },
        { name: "Skyline", genre: "Heavy Metal" },
        { name: "Skynd", genre: "Industrial Metal" },
        { name: "Spectral Wound", genre: "Black Metal" },
        { name: "Stonem", genre: "Metalcore" },
        { name: "Storm Seeker", genre: "Folk Metal" },
        { name: "Subway To Sally", genre: "Medieval Metal" },
        { name: "Sót", genre: "Stoner / Sludge Metal" },
        { name: "Temple Of The Absurd", genre: "Thrash Metal" },
        { name: "The Butcher Sisters", genre: "Metalcore" },
        { name: "The Crescent's Call", genre: "Symphonic Folk Metal" },
        { name: "The Gathering", genre: "Alternative Rock" },
        { name: "The Hardkiss", genre: "Alternative Rock" },
        { name: "The Haunted", genre: "Thrash Metal" },
        { name: "The Limit", genre: "Hard Rock" },
        { name: "The Other", genre: "Horror Punk" },
        { name: "The Troops Of Doom", genre: "Death Metal" },
        { name: "Therapy?", genre: "Alternative Rock" },
        { name: "Thrown", genre: "Metalcore" },
        { name: "Thundermother", genre: "Hard Rock" },
        { name: "Thy Art Is Murder", genre: "Deathcore" },
        { name: "Triptykon", genre: "Doom Metal" },
        { name: "Trold", genre: "Folk-Metal" },
        { name: "Turbonegro", genre: "Punk Rock" },
        { name: "Tuxedoo", genre: "Metalcore" },
        { name: "Uli Jon Roth", genre: "Hard Rock" },
        { name: "Unzucht", genre: "Dark Rock" },
        { name: "Vanir", genre: "Folk Metal" },
        { name: "Velvet Rush", genre: "Hard Rock" },
        { name: "Vended", genre: "Alternative Metal" },
        { name: "VDouble-check", genre: "Symphonic Metal" },
        { name: "Visions Of Atlantis", genre: "Symphonic Metal" },
        { name: "Vogelfrey", genre: "Folk Metal" },
        { name: "Wacken Firefighters", genre: "Metal Meets Brass" },
        { name: "Wytch Hazel", genre: "Heavy Metal" },
        { name: "Wüstenberg", genre: "Folk Rock" },
        { name: "Year Of The Goat", genre: "Hard Rock" },
        { name: "Yngwie Malmsteen", genre: "Neoclassical Metal" },
        { name: "Zeltinger Band", genre: "Rock" },
        { name: "ten56.", genre: "Deathcore" }
    ]
};
// Append this to the bottom of your existing database.js file
const TOURS_DATA_REGISTRY = {
    "Europe": [
        { band: "Gojira", dates: "October - December 2026", venues: "24 Arena Dates", status: "Selling Fast" },
        { band: "Lorna Shore", dates: "November 2026", venues: "12 European Cities", status: "Headline Tour" },
        { band: "Electric Callboy", dates: "Staged 2026", venues: "Continental Fest Runs", status: "Confirmed" }
    ],
    "USA": [
        { band: "Metallica", dates: "August - September 2026", venues: "M72 Stadium Extensions", status: "Major Event" },
        { band: "Spiritbox", dates: "September 2026", venues: "18 Amphitheater Dates", status: "Support Slots Available" }
    ],
    "Australia": [
        { band: "Parkway Drive", dates: "December 2026", venues: "Anniversary Arena Tour", status: "Homecoming Tour" },
        { band: "Amity Affliction", dates: "January 2027", venues: "East Coast Brisbane/Sydney/Melb", status: "Announced" }
    ]
};